version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile-python
    depends_on:
      - mysql
    restart: always
    container_name: python-app

  mysql:
    build:
      context: .
      dockerfile: Dockerfile-mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: testdb
    ports:
      - "3306:3306"
    container_name: mysql-db
    restart: always
