# Dockerfile for MySQL Database
FROM mysql:latest

# Set environment variables
ENV MYSQL_ROOT_PASSWORD=password
ENV MYSQL_DATABASE=testdb

# Copy SQL script to create the table
COPY init.sql /docker-entrypoint-initdb.d/
